// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0JfqF6XMEAxJIbwCE7jeU-qLoD-7GKlc',
    appId: '1:556801094258:web:a33777d28461c9e5e9c8eb',
    messagingSenderId: '556801094258',
    projectId: 'society-372a2',
    authDomain: 'society-372a2.firebaseapp.com',
    storageBucket: 'society-372a2.firebasestorage.app',
    measurementId: 'G-F7RYCCLSV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfO9sDM3yA7ciTOaIFiRqXH4natXmO3pc',
    appId: '1:556801094258:android:92b568edc391b3ede9c8eb',
    messagingSenderId: '556801094258',
    projectId: 'society-372a2',
    storageBucket: 'society-372a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPRuh9u5Pe_gSzwMYE3ShsrTL1ryXvvAI',
    appId: '1:556801094258:ios:6f33535906782945e9c8eb',
    messagingSenderId: '556801094258',
    projectId: 'society-372a2',
    storageBucket: 'society-372a2.firebasestorage.app',
    iosBundleId: 'com.example.societyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPRuh9u5Pe_gSzwMYE3ShsrTL1ryXvvAI',
    appId: '1:556801094258:ios:6f33535906782945e9c8eb',
    messagingSenderId: '556801094258',
    projectId: 'society-372a2',
    storageBucket: 'society-372a2.firebasestorage.app',
    iosBundleId: 'com.example.societyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0JfqF6XMEAxJIbwCE7jeU-qLoD-7GKlc',
    appId: '1:556801094258:web:11700c8a4050903fe9c8eb',
    messagingSenderId: '556801094258',
    projectId: 'society-372a2',
    authDomain: 'society-372a2.firebaseapp.com',
    storageBucket: 'society-372a2.firebasestorage.app',
    measurementId: 'G-XE5ZJ29XZS',
  );
}
